In [1]:
# What does one need to do to use a module?
import pandas as pd
# Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.
green = pd.read_csv('./resources/GREENCOMPUTERS500.csv',index_col=0)
green.info()
green
# What is a benefit of using Exception handling?
Seperating Error-Handling Code from regular code
# NumPy arrays are like what Python data type?
lists
# What is one of the main benefits of using NumPy arrays.
Use on large datasets
# What is one of the main requirements about the 'dtype' of NumPy arrays?
need the same datatypes
# Of the 10 uses of NumPy, name 2.
Rounding and degrees/radius
# Name one of the other libraries we'll use with NumPy?
Pandas
# What is the shape of NumPy arrays?
The number of rows and columns in the array
# What is a Tensor?
3d array
# Name a reason why it's better using NumPy for Data Analysis than using a Python List?
It is faster than a python list
# When creating an "empty" array, where do the elements come from?
They are random
# What does Pandas stand for?
Pediatric Autoimmune Neuropsychiatric Disorders Associated with Streptococcal Infections.
# What are the 2 collections used in Pandas?
Series and dataframe
# Name 4 things Pandas can do for us.
data visuaiztion, math operations, machine learning, and data analysis
# To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
in place= true
# What is a CSV
commoa seperated value
# When cleaning data what values do we not like in our data?
Null

SyntaxError: invalid decimal literal (192648268.py, line 22)

In [27]:
import numpy as np

#1

A = np.array([[25, 16]])
B = np.array([[11, 2], [13, 4]])
C = np.array([[7, 81], [5, 6], [11, 12]])

#2

newArray = np.concatenate((A, B, C))
print(newArray)

#3

sortedArray = np.sort(newArray)
print("\n", sortedArray)

#4

reshapedArray = sortedArray.reshape(2,2,3)
print("\n", reshapedArray)

#5

import numpy as np


d, e = reshapedArray

a0, a1 = d
b0, b1 = e
print("\nUnpacked tuple into 4 variables...", a0)
print(a1)
print(b0)
print(b1)

#6

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate(((one, two, three)))
print(comboArray)

print("Number of Elements...", len(comboArray))
sec1 = comboArray[2]
print("sec1...", sec1)
sec2 = comboArray[3:24]
print("sec2...", sec2)
sec3 = comboArray[4:15]
print("sec3...", sec3)
sec4 = comboArray[-6:]
print("sec4...", sec4)
sec5 = comboArray[:-8]
print("sec5...", sec5)
sec6 = comboArray[20:25:2]
print("sec6...", sec6)
sec7 = comboArray[::-5]
print("sec7...", sec7)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

Unpacked tuple into 4 variables... [16 25  2]
[11  4 13]
[ 7 81  5]
[ 6 11 12]
[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
Number of Elements... 24
sec1... 12
sec2... [13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
sec3... [14 15 16 17 20 21 22 23 24 25 26]
sec4... [2 3 4 5 6 7]
sec5... [10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec6... [4 6]
sec7... [ 7  2 25 20 13]


In [31]:

#7

import numpy as np

Array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

Array2 = np.array([[17.0, 70.0, 10.7]])

Addition = np.add(Array1, Array2)
print("Addition: \n", Addition)

Division = np.divide(Array1, Array2)
print("\n Division: \n", Division)

Times = np.multiply(Array1, Array2)
print("\n Multiplication: \n", Times)


#8

Subtraction = np.subtract(Array1, Array2)
print("\n Subtraction: \n", Subtraction)

#9 

Divisible1 = Array1[Array1 % 3 == 0]
print("\n Divisible by 3 for Array 1: \n", Divisible1)






Addition: 
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

 Division: 
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

 Multiplication: 
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

 Subtraction: 
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]

 Divisible by 3 for Array 1: 
 [ 0.  0. 30. 24. 15.]


In [ ]:
#10

import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name='Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name='Quantity')
Unit = pd.Series(["cups", "cup", "large", "can"], name='Unit')

index_labels = ["Item 1", "Item 2", "Item 3", "Item 4"]
Ingredients.index = index_labels
Quantity.index = index_labels
Unit.index = index_labels

Dinner = pd.concat([Ingredients,Quantity,Unit], axis=1)
print(Dinner)

In [ ]:
import pandas as pd

# 11

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(data)
print(studentData)

#12

studentData.insert(7, "Desserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], True)
print("\n", studentData)

#13

studentData.sort_values(by = ['Name'], inplace = True)
print("\n Sorted by Name: \n", studentData)

studentData.sort_values(by = ['address'], inplace = True)
print("\n Sorted by Address: \n", studentData)

In [35]:
import pandas as pd

#14

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv', index=False)
df_saved_file = pd.read_csv('cows_and_goats.csv')

ModuleNotFoundError: No module named 'pandas'

In [36]:
vegTable = {
        'vegetable': ["carrots", "beets", "peas", "pumpkin"],
        'color': ["orange", "purple", "green", "orange"]
        }

vegDF=pd.DataFrame(vegTable)
print(vegDF)
vegDF.to_csv('Veggie_colors.csv', index=True)

vegDF.loc[3, "color"]="yellow-orange"

print("\n Updated dataframe\n",vegDF)
vegDF.to_csv('Veggie_colors2.csv', index=True)

NameError: name 'pd' is not defined